### ISSUE TITLE
Checked on Windows 10 Machine

### ISSUE THREAD

**Issue by aurielfournier** [weecology/ratdat#1]
Package looks great, just added in some more details on the `surveys` dataset so the columns are explained in the help files.

I tested the installation on my Windows 10 machine, running R Version 3.4.3 and it worked great. 

Happy to help expand this out if anyone else seems other needs. Just ping me.

**Comment by ethanwhite** [comment]
Awesome! Thanks @aurielfournier - and if you see anything to improve, please go for it. Once you and @fmichonneau are happy with the state of this for your lessons let me know and we can work on getting it up on CRAN.
